spring.application.name=membershipprogram
spring.datasource.url=jdbc:mysql://localhost:3306/membership_program
spring.datasource.username=root
spring.datasource.password=rootpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true