CREATE TABLE membership_plan (
     id BIGINT AUTO_INCREMENT PRIMARY KEY,

     plan_code VARCHAR(50) NOT NULL UNIQUE,
     plan_name VARCHAR(100) NOT NULL,

     price DECIMAL(10,2) NOT NULL,

     duration_days INT NOT NULL,

     active BOOLEAN NOT NULL DEFAULT TRUE,

     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
         ON UPDATE CURRENT_TIMESTAMP
);