CREATE TABLE membership_tier (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    tier_code VARCHAR(50) NOT NULL UNIQUE,
    tier_name VARCHAR(100) NOT NULL,

    priority INT NOT NULL,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
);